### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'. when launching agent

### ISSUE THREAD

**Issue by satyamedh** [facebookresearch/craftassist#12]
I am getting 

Traceback (most recent call last):
  File "./python/craftassist/craftassist_agent.py", line 27, in <module>
    import memory
  File "/root/craftassist/python/craftassist/memory.py", line 23, in <module>
    import dance
  File "/root/craftassist/python/craftassist/dance.py", line 9, in <module>
    import tasks
  File "/root/craftassist/python/craftassist/tasks.py", line 18, in <module>
    from perception import ground_height
  File "/root/craftassist/python/craftassist/perception.py", line 24, in <module>
    BLOCK_DATA = minecraft_specs.get_block_data()
  File "/root/craftassist/python/craftassist/minecraft_specs.py", line 24, in get_block_data
    _BLOCK_DATA = _pickle_load("block_images/block_data")
  File "/root/craftassist/python/craftassist/minecraft_specs.py", line 68, in _pickle_load
    return pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.
when launching the agent please help

I am using WSL ubuntu 18.04 and following this guide:
https://jas-team.net/2019/09/15/compile-and-use-facebook-researchs-craftassist/

please help

**Comment by satyamedh** [comment]
@jonbaer, can you help me with this?

**Comment by jonbaer** [comment]
Those instructions you are using from that link are either old or out-of-date, you need to see the project readme where it says to install git-lfs before you even begin ... git lfs clone --recursive git@github.com:facebookresearch/craftassist.git ... that would be my best guess.

**Comment by satyamedh** [comment]
@jonbaer, thanks I'll check it out

**Comment by drothermel** [comment]
Thanks for creating this issue, this is a result of an problem we're currently fixing with git-lfs (so, even if you've installed git-lfs and use it to clone, this error will arise).  We're working on the fix now and will let you know when it's ready!

**Comment by satyamedh** [comment]
@drothermel thanks, any estimate when it will be ready?

**Comment by drothermel** [comment]
I'd estimate 1-2 days, ideally sooner

**Comment by satyamedh** [comment]
@drothermel, ready?

**Comment by drothermel** [comment]
We have the fix ready in our internal repository, but unfortunately we're blocked from pushing to the external repository due to our git-lfs data quota.  We need additional internal teams to fix this problem but due to the holidays this has been delayed by a few days.  Sorry for the delay and we'll keep you updated when we push the fix.

**Comment by afree2004** [comment]
@drothermel  Hello i also encountered the same problem, when will it be resolved. Thank you.

**Comment by afree2004** [comment]
@drothermel Can you open your changes as a branch? Can't wait to test it.

**Comment by drothermel** [comment]
We just got word, this should be fixed.  Please try pulling again, and if that doesn't work re-cloning should fix the problem.  Thank you for your patience and please let us know if there is still an issue!

**Comment by drothermel** [comment]
Also note that you will likely need to follow the following build instructions for this to work (we'll be pushing an update including this in the README on Monday):

First, update the requirements.txt file to contain the following:
```
awscli==1.15.7
black==18.9b0
botocore==1.10.7
cython==0.29.14
decorator==4.3.0
docopt==0.6.2
docutils==0.14
flake8==3.5.0
flake8-mypy==17.8.0
ipdb==0.11
ipython-genutils==0.2.0
ipython==6.3.1
joblib==0.11
matplotlib==2.2.2
mypy-extensions==0.4.1
mypy==0.701
numpy==1.14.2
python-Levenshtein==0.12.0
python-dateutil==2.7.2
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.1.0
sentry-sdk==0.7.9
six==1.11.0
snowballstemmer==1.2.1
spacy==2.0.12
tqdm==4.23.4
word2number==1.1
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
```

Then, after making sure you have the dependencies listed in the "Dependencies" section of the readme, use conda to create a new env preloaded with the conda install deps and activate the env:
```
conda create -n minecraft_env python==3.7.4 pip numpy scikit-learn==0.19.1 pytorch torchvision -c conda-forge -c pytorch
conda activate minecraft_env
```

Then, install the rest of the deps with pip:
```
while read requirement; do echo $requirement; pip install $requirement; done < requirements.txt
```

The versions specified above, installed in this order should work and solve the no module named agent issue (but let us know if this is not the case)!

**Comment by satyamedh** [comment]
@drothermel, still have the unpickling error

**Comment by Steve-Tech** [comment]
> Those instructions you are using from that link are either old or out-of-date, you need to see the project readme where it says to install git-lfs before you even begin ... git lfs clone --recursive [git@github.com](mailto:git@github.com):facebookresearch/craftassist.git ... that would be my best guess.

Sorry, I was the author of that article, when I have the time I'll update it.

**Comment by drothermel** [comment]
Ok, we just did a push and I stepped through the new instructions in the README start to finish to ensure that it worked for me from a clean conda env and build.

Would you please pull and then specifically do the new instructions under "Python Requirements: Using a Conda Environment" through "Checking out the repo" (the curl and tar commands to get the model data files) and let me know if you're still getting the unpickling error?

Specifically, if you're still having that issue could you please run "ls minecraft_specs/block_images/" from the top level directory?

**Comment by satyamedh** [comment]
@drothermel, the bot joins the game but doesn't respond to anything/any action

**Comment by drothermel** [comment]
Hi @satyamedh, thanks for the update.  Can you do the following please to help me debug:

Run the following from the top level of your directory and paste the output here:
1) `conda list`
2) `ls -la python/craftassist/models/`
3) `ls -la python/craftassist/models/ttad/`
3) `./python/craftassist/test.sh`

Also, the full output when you start the bot and issue commands from both the server (`python ./python/cuberite_process.py`) and the client (`python ./python/craftassist/craftassist_agent.py`).

From there I can try to debug this further, thank you!

**Comment by satyamedh** [comment]
@drothermel 


conda list:https://pastebin.com/iCHvd6pF
ls -la python/craftassist/models/ : https://pastebin.com/YepB5xVy
ls -la python/craftassist/models/ttad/: https://pastebin.com/tibjteXe
./python/craftassist/test.sh : https://pastebin.com/iVgzuz2r
.....................
and after I started the server and client, turns out, it was an issue for lag, thanks for helping though

**Comment by drothermel** [comment]
@satyamedh, to confirm, you're saying it works for you now?

**Comment by satyamedh** [comment]
@drothermel yep, it was an issue of lag, thanks, closing this issue now
