### ISSUE TITLE
ModuleNotFoundError: No module named 'agent'

### ISSUE THREAD

**Issue by Minecon724** [facebookresearch/craftassist#13]
Traceback (most recent call last):
  File "python/craftassist/craftassist_agent.py", line 22, in <module>
    from agent import Agent
ModuleNotFoundError: No module named 'agent'

**Comment by drothermel** [comment]
Hello, thanks for making an issue! This is a known issue and we have a fix internally that we will hopefully be pushing in the next day or two.  We'll update you when the fix is out, and if the setup process still doesn't work then we can investigate what else might be wrong.  Thanks for your patience!

**Comment by drothermel** [comment]
Ok, you should actually be able to fix this issue without a push if you're willing to make some manual changes.  First, update the requirements.txt file to contain the following:
```
awscli==1.15.7
black==18.9b0
botocore==1.10.7
cython==0.29.14
decorator==4.3.0
docopt==0.6.2
docutils==0.14
flake8==3.5.0
flake8-mypy==17.8.0
ipdb==0.11
ipython-genutils==0.2.0
ipython==6.3.1
joblib==0.11
matplotlib==2.2.2
mypy-extensions==0.4.1
mypy==0.701
numpy==1.14.2
python-Levenshtein==0.12.0
python-dateutil==2.7.2
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.1.0
sentry-sdk==0.7.9
six==1.11.0
snowballstemmer==1.2.1
spacy==2.0.12
tqdm==4.23.4
word2number==1.1
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
```

Then, after making sure you have the dependencies listed in the "Dependencies" section of the readme, use conda to create a new env preloaded with the conda install deps and activate the env:
```
conda create -n minecraft_env python==3.7.4 pip numpy scikit-learn==0.19.1 pytorch torchvision -c conda-forge -c pytorch
conda activate minecraft_env
```

Then, install the rest of the deps with pip:
```
while read requirement; do echo $requirement; pip install $requirement; done < requirements.txt
```

The versions specified above, installed in this order should work and solve the no module named agent issue (but let us know if this is not the case)!

**Comment by kavyasrinet** [comment]
Hi @Minecon724, can you please confirm if the above instructions helped ?

**Comment by Minecon724** [comment]
I will check it tomorrow.

**Comment by drothermel** [comment]
Hi @Minecon724, we actually just did a push, so instead of trying the above commands please pull and then follow the new instructions under "Python Requirements: Using a Conda Environment" through "Checking out the repo" (the curl and tar commands to get the model data files) and let me know if you're still having issues?

**Comment by Minecon724** [comment]
![Zrzut ekranu z 2020-01-14 19-06-57](https://user-images.githubusercontent.com/39800107/72369784-1ed51f00-3701-11ea-87d7-8018ef9edd53.png)

**Comment by Minecon724** [comment]
File "./python/craftassist/craftassist_agent.py", line 350
    def _send_chat(self, chat: str):
                             ^
SyntaxError: invalid syntax

**Comment by Minecon724** [comment]
or with python 3

**Comment by Minecon724** [comment]
Traceback (most recent call last):
  File "./python/craftassist/craftassist_agent.py", line 22, in <module>
    from agent import Agent
ModuleNotFoundError: No module named 'agent'

**Comment by drothermel** [comment]
Hi @Minecon724, thanks for the update. Lets continue with the python 3 version, can you do the following please to help me debug:

Run the following from the top level of your directory and paste a link to the output here:
- `conda list`
- `ls -la python/`
- `./python/craftassist/test.sh`

And to verify, you followed the instructions on the new README not the ones that I linked above, right?

From there I can try to debug this further, thank you!

**Comment by Minecon724** [comment]
Everything is working fine now. I just restart the computer.

**Comment by drothermel** [comment]
Great, thanks!  I'll close the issue then but please feel free to reopen or make a new one if you have more trouble!

**Comment by pste22** [comment]
> Checking out the repo

hi @drothermel , I am facing the issue and trying to resolve 
where exactly is the below located ?
"Python Requirements: Using a Conda Environment" through "Checking out the repo" ?

**Comment by sindujanarra** [comment]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/carla/Backup-1/carla/PythonAPI/si_examples/automatic_control.py", line 63, in <module>
    from agents.navigation.roaming_agent import RoamingAgent
ImportError: No module named agents.navigation.roaming_agent

**Comment by kavyasrinet** [comment]
Hi @sindujanarra ! Can you please elaborate more on the issue you are facing ?
As a heads up - we have now migrated the `craftassist` codebase to be here: https://github.com/facebookresearch/droidlet/craftassist  and we will be maintaining this repo going forward. We ask that you please switch to the droidlet repo going forward.
Please feel free to reopen the issue there if you see an issue.
