### ISSUE TITLE
Error when building wheel for numpy ( pip install -r requirements.txt)

### ISSUE THREAD

**Issue by afree2004** [facebookresearch/craftassist#15]
Building wheels for collected packages: numpy, en-core-web-sm
  Building wheel for numpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/afree2004/miniconda2/envs/minecraft_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ihxcmcx3/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ihxcmcx3/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4adosgd8 --python-tag cp37
       cwd: /tmp/pip-install-ihxcmcx3/numpy/
  Complete output (3846 lines):
  Running from numpy source directory.
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/home/afree2004/miniconda2/envs/minecraft_env/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/home/afree2004/miniconda2/envs/minecraft_env/include']

    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/home/afree2004/miniconda2/envs/minecraft_env/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/home/afree2004/miniconda2/envs/minecraft_env/include']

  /bin/sh: 1: svnversion: not found
  non-existing path in 'numpy/distutils': 'site.cfg'
  /bin/sh: 1: svnversion: not found
  F2PY Version 2

My bash history is as follows:
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install cmake python3 python3-pip libgoogle-glog-dev libboost-all-dev libeigen3-dev
gcc --version
bash Miniconda2-latest-Linux-x86_64.sh
conda create -n minecraft_env python==3.7.4 pip numpy scikit-learn==0.19.1 pytorch torchvision -c conda-forge -c pytorch
conda activate minecraft_env
pip install -r requirements.txt

**Comment by drothermel** [comment]
Hello @afree2004, thanks for making this issue!

I believe the problem is a result of a mismatch in numpy versions requested, I just merged #16 to solve this issue (it now works locally for me).  Please pull (or manually fix the one line in requirements.txt) and let us know whether this fixes your issue!

**Comment by afree2004** [comment]
@drothermel , ok, i'll check it out. Thanks.

**Comment by afree2004** [comment]
@drothermel It works for me now. Close this issue.
