### ISSUE TITLE
Model load error (craftassist_agent.py)

### ISSUE THREAD

**Issue by kepolol** [facebookresearch/craftassist#20]
This error i can see, when try to run craftassist_agent.py.
The file caip_test_model.pth include decoder.lm_head.predictions.decoder.weight, but decoder.lm_head.predictions.decoder.bias is absent.

Traceback (most recent call last):
  File "./python/craftassist/craftassist_agent.py", line 436, in <module>
    geoscorer_model_path=opts.geoscorer_model_path,
  File "./python/craftassist/craftassist_agent.py", line 117, in __init__
    ttad_grammar_path,
  File "/home/ivan/craftassist/python/craftassist/ttad_model_dialogue_manager.py", line 76, in __init__
    self.ttad_model = TTADBertModel(model_dir=ttad_model_dir, data_dir=ttad_bert_data_dir)
  File "/home/ivan/craftassist/python/craftassist/ttad/ttad_transformer_model/query_model.py", line 38, in __init__
    torch.load(model_name + ".pth", map_location=map_location)
  File "/home/ivan/craftassist/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EncoderDecoderWithLoss:
	Missing key(s) in state_dict: "decoder.lm_head.predictions.decoder.bias".

**Comment by satyamedh** [comment]
try rerunning make

hope it helps

**Comment by kavyasrinet** [comment]
Hi @kepolol ,
Thanks for creating the issue.
I just tried cloning the repo from scratch  and followed the steps here: https://github.com/facebookresearch/craftassist#checking-out-the-repo


Just to make sure, can you please do the following:
```
cd minecraft/
git pull origin master
rm -rf python/craftassist/models/*
```
and then do the following:
```
curl http://craftassist.s3-us-west-2.amazonaws.com/pubr/models_folder.tar.gz -o models_folder.tar.gz
tar -xzvf models_folder.tar.gz -C python/craftassist/models/ --strip-components 1
curl http://craftassist.s3-us-west-2.amazonaws.com/pubr/ground_truth_data.txt -o python/craftassist/ground_truth_data.txt
```
as mentioned in our updated [README](https://github.com/facebookresearch/craftassist#checking-out-the-repo)

and then try:
```
python ./python/cuberite_process.py
```
to start the server and 
```
python ./python/craftassist/craftassist_agent.py
```
to start the bot process ?

If the error still persists:
1. In the log of  `python ./python/craftassist/craftassist_agent.py` , can you confirm that you see:
```
"using ttad_model_dir=./python/craftassist/models/ttad_bert/model/"
```
2. Can you confirm that your pytorch version is 1.1.0 ? You can check that by doing:
```
python
import torch
torch.__version__
```

**Comment by kepolol** [comment]
Hello, @kavyasrinet ! Thanks for your reply!
I try to run craftassist_agent.py eith your guide on my Ubunty 19.04 (torch==1.1.0) and WSL Ubunty 18.04 LTS(torch==1.4.0), but this steps lead to decoder error.
In logs i can see message like this
"""
2020-02-05 09:50:36,479 [ttad_model_dialogue_manager.py:64 - __init__() INFO]: using ttad_model_dir=./python/craftassist/models/ttad_bert/model/
"""
on all my systems.
P.S.: maybe I do not quite understand the command 'cd minecraft', and use 'cd craftassist'(root dir 4 repo)

**Comment by kepolol** [comment]
Hello, @satyamedh ! Thanks for your reply! But it's not work for me.

**Comment by kavyasrinet** [comment]
Hi @kepolol ,
Thanks for sending the detailed log.
I'm using Ubuntu 18.04 as well and same pytorch version, however I still cannot reproduce the issue.
This looks like a pytorch problem.

On your local filesystem can you please try editing [this line](https://github.com/facebookresearch/craftassist/blob/master/python/craftassist/ttad/ttad_transformer_model/query_model.py#L36)
to: 
```
self.encoder_decoder.load_state_dict(
            torch.load(model_name + ".pth", map_location=map_location), strict=False
        )
```
and try again ?

**Comment by kepolol** [comment]
Hello, @kavyasrinet ! Thank you very much! strict=False solve the problem.

**Comment by kavyasrinet** [comment]
Thanks a lot!
Do you want to create a pull request with the above change ? If not, we'll make sure to push in the next commit.

**Comment by kepolol** [comment]
Thank you! I wish create a pull request!
