### ISSUE TITLE
Agent crashes as soon as it joins

### ISSUE THREAD

**Issue by odm7341** [facebookresearch/craftassist#24]
[https://pastebin.com/j0e5cxCu](https://pastebin.com/j0e5cxCu)

It seems like its an issue with memory.py

**Comment by aszlam** [comment]
This will be fixed in next push (v. soon!)

**Comment by snyxan** [comment]
Hi @odm7341 ,

Could you please confirm if our latest push solves your issue?

**Comment by kavyasrinet** [comment]
Hi @odm7341 !
Following up on @snyxan comment above and checking in if our latest commit fixed the issue mentioned.

**Comment by odm7341** [comment]
Yes, I can confirm the the bot no longer crashes

**Comment by snyxan** [comment]
Great, thanks! I'll close the issue then but please feel free to reopen or make a new one if you have more trouble!
