### ISSUE TITLE
Making and runing the cuberite server

### ISSUE THREAD

**Issue by akshay-sharma1995** [facebookresearch/craftassist#25]
I am not able to make the cuberite server. When I run `make` in the root directory of craftassist, it gives me this error:
![Screenshot from 2020-02-25 18-12-40](https://user-images.githubusercontent.com/13129062/75296297-c19db480-57fa-11ea-8cfa-99e7751e4a8c.png)

To resolve this I tried to download and compile cuberite according to the instructions given on the cuberite github repo [https://github.com/fairinternal/cuberite](url)
After this the make command runs for a while and then give me the following error:
![Screenshot from 2020-02-25 18-18-26](https://user-images.githubusercontent.com/13129062/75296463-3ffa5680-57fb-11ea-810c-77180da89c29.png)
When I try to run the cubernite server just to check whether it works or not by running `python ./python/cuberite_process.py` it gives me this:
![Screenshot from 2020-02-25 18-20-47](https://user-images.githubusercontent.com/13129062/75296578-92d40e00-57fb-11ea-9256-c100450b6a31.png)

I am not sure how to resolve this issue.

**Comment by snyxan** [comment]
Hi @akshay-sharma1995, Glad to help here!

Could you please confirm you have installed&initialized git-lfs properly and clone our repo with git-lfs?

**Comment by akshay-sharma1995** [comment]
Hey @snyxan, I did install and initialize git-lfs as mentioned in Readme, but after that when I try to clone the repo using `git lfs clone --recursive git@github.com:facebookresearch/craftassist.git` I get `git@github.com: Permission denied (publickey)` error:
![Screenshot from 2020-02-25 19-48-02](https://user-images.githubusercontent.com/13129062/75301255-4d6a0d80-5808-11ea-8dbe-fa4ec4433a7f.png)

Due to this I used git clone to clone the repo. I have not used git-lfs earlier so sorry if it is some trivial stuff.

**Comment by snyxan** [comment]
Hi @akshay-sharma1995 ,

Using git-lfs to clone our repo is required since it will pull all the submodules (e.g. cuberite, pybind11) we are depending on. A 'Permission denied' means the github server rejected your connection. Please refer to https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey to solve your problem.

**Comment by akshay-sharma1995** [comment]
Hey @snyxan, thanks a lot, this did work, I was able to use git-lfs. But then I got stuck at another issue. Now when I run make it runs for a while, and I guess it is able to make cuberite but then throws this error: 
![Screenshot from 2020-02-25 21-28-31](https://user-images.githubusercontent.com/13129062/75306021-d0459500-5815-11ea-8471-4e0bd0474891.png)

**Comment by akshay-sharma1995** [comment]
Hey @snyxan, I had one more question, as mentioned in the last comment I was able to start the server by running cuberite_process.py even when the error while make still exists, but when I tried to connect the client with the server, it shows "logging in" for a while and then shows "Connection Lost" even when the server is running. I am using Malmo with Minecraft 1.11.2 as the client. Will this setup work with Malmo given that you have mentioned that one should buy the minecraft client and then use it?

**Comment by snyxan** [comment]
> Hey @snyxan, I had one more question, as mentioned in the last comment I was able to start the server by running cuberite_process.py even when the error while make still exists, but when I tried to connect the client with the server, it shows "logging in" for a while and then shows "Connection Lost" even when the server is running. I am using Malmo with Minecraft 1.11.2 as the client. Will this setup work with Malmo given that you have mentioned that one should buy the minecraft client and then use it?

Hi, @akshay-sharma1995 ,
Being able to run cuberite_process.py means your cuberite thing is set up properly and you should be able to connect to the server from a Minecraft client (despite of other errors like failing to build the agent). I'm not sure what setup work Malmo does but in our setting, you just simply need a Minecraft client with v1.12 or lower. Is it possible for you to run Minecraft client without Malmo's work?

**Comment by scatterp** [comment]
$ sudo apt-get install libgflags2 libgflags
then rebuild cubite should fix your error
also edit config file to login it's 
settings.ini or world.ini I forget which 
set game mode to offline 
hope this helps let me knoe

**Comment by snyxan** [comment]
> $ sudo apt-get install libgflags2 libgflags
> then rebuild cubite should fix your error
> also edit config file to login it's
> settings.ini or world.ini I forget which
> set game mode to offline
> hope this helps let me knoe




> Hey @snyxan, thanks a lot, this did work, I was able to use git-lfs. But then I got stuck at another issue. Now when I run make it runs for a while, and I guess it is able to make cuberite but then throws this error:
> ![Screenshot from 2020-02-25 21-28-31](https://user-images.githubusercontent.com/13129062/75306021-d0459500-5815-11ea-8471-4e0bd0474891.png)
> But the cuberite_process.py file does run and starts the server, so I am not entirely sure whether this is something like a warning or an error that needs to be resolved.

Great! This error means the linker can't find gflags library while building the agent (which also indicates you have built the cuberite server successfully)

Try ```$ sudo apt-get install libgflags2 libgflags``` as @scatterp suggested(Thanks @scatterp !) to see if it solves your problem. You do not need to rebuild the cuberite though.

**Comment by akshay-sharma1995** [comment]
Hey @snyxan, @scatterp thanks for the help. I was able to get the gflags error go away by your solution, but the Malmo client is still not able to connect to the cuberite server. 

> Hi, @akshay-sharma1995 ,
> Being able to run cuberite_process.py means your cuberite thing is set up properly and you should be able to connect to the server from a Minecraft client (despite of other errors like failing to build the agent). I'm not sure what setup work Malmo does but in our setting, you just simply need a Minecraft client with v1.12 or lower. Is it possible for you to run Minecraft client without Malmo's work?

@snyxan, I have not yet bought the Minecraft client, I was trying to try out your work and see how it will fit my research before going to buy the Minecraft client. 

@scatterp, the settings.ini, and world.ini files you are talking about are present in craftassist/cuberite_config/<world_type> where <world_type> is one of the world folders in the directory. Am I right? But I don't see any gamemode tag in any of those files. Am I looking at the wrong location?

**Comment by scatterp** [comment]
will check exactly tommorow

**Comment by scatterp** [comment]
https://github.com/facebookresearch/craftassist/blob/d7513f89f9e03a5f007dffc80c5106c7bdcc0498/cuberite_config/housebuild/settings.ini#L7

**Comment by scatterp** [comment]
in which ever world you run

**Comment by akshay-sharma1995** [comment]
@scatterp, I did check the settings.ini as you mentioned. The "Authenticate " tag was already set to 0 in all the worlds. Though I am not sure how do I select any of those world specifically while starting the server. The Readme.txt file iniside the cuberite_config directory says
 `Make a copy of the flat_world directory and run Cuberite from inside this copy.
Non-default config parameters will be filled in and a new world will be
generated. Do not commit this generated world to the repo!`
I tried starting the cuberite server after cd into the cuberite_config/flat_world directory but I am still not able to connect the Malmo client with the cuberite server.
@snyxan , @scatterp I am also attaching the output after running the cuberite_process.py file if you could find something in that which I am missing.
![Screenshot from 2020-02-29 16-51-30](https://user-images.githubusercontent.com/13129062/75615604-e2744b80-5b13-11ea-8da8-91304e89b32c.png)
Else I think I might have to buy the Minecraft client and try it out.

**Comment by satyamedh** [comment]
> Hey @snyxan, I had one more question, as mentioned in the last comment I was able to start the server by running cuberite_process.py even when the error while make still exists, but when I tried to connect the client with the server, it shows "logging in" for a while and then shows "Connection Lost" even when the server is running. I am using Malmo with Minecraft 1.11.2 as the client. Will this setup work with Malmo given that you have mentioned that one should buy the Minecraft client and then use it?

it won't work. because it is v1.11.2, the server is v1.12.2. the only option is to buy mc.


note: 

> malmo is built on forge, they provide a version of mc used just for testing. these versions don't include support for multiplayer support. so you are better off buying mc

**Comment by satyamedh** [comment]
@akshay-sharma1995 , check out this^^^^

**Comment by scatterp** [comment]
I would discuss this on discord with cubite team it's not really craftassist question anymore ask about via type solution

**Comment by akshay-sharma1995** [comment]
@satyamedh, I guess I will  buy the MC client then and check again. Though I am not sure about the problem being Malmo using v1.11.2 of Minecraft as the cuberite server does say it supports 1.11.x clients. It must be the multiplayer support issue. I will try it after buying MC and let you know. Still thanks for the help @snyxan @scatterp @satyamedh 
Also @satyamedh, if you find anything useful from discord discussion please let me know.

**Comment by akshay-sharma1995** [comment]
Hey @scatterp, @snyxan, @satyamedh, I bought the Minecraft client and it works now. I guess the issue is with malmo.
If you find any way to make it work malmo please let me know about that.
Apart from that I guess this issue can be closed. 
Thanks a lot.

**Comment by snyxan** [comment]
> Hey @scatterp, @snyxan, @satyamedh, I bought the Minecraft client and it works now. I guess the issue is with malmo.
> If you find any way to make it work malmo please let me know about that.
> Apart from that I guess this issue can be closed.
> Thanks a lot.

Hi @akshay-sharma1995 ,

Glad to hear it works now. Enjoy playing with our bot!
