### ISSUE TITLE
fatal error: glog/logging.h: No such file or directory

### ISSUE THREAD

**Issue by yutongyan** [facebookresearch/craftassist#4]
Hey! I got this error but I have no idea why this error ocurred since I already have glog installed.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/yyt/Downloads/craftassist/client
make[1]: Entering directory '/home/yyt/Downloads/craftassist/client'
make[2]: Entering directory '/home/yyt/Downloads/craftassist/client'
make[3]: Entering directory '/home/yyt/Downloads/craftassist/client'
make[3]: Leaving directory '/home/yyt/Downloads/craftassist/client'
make[3]: Entering directory '/home/yyt/Downloads/craftassist/client'
[  7%] Building CXX object CMakeFiles/agent.dir/src/agent.cpp.o
/home/yyt/Downloads/craftassist/client/src/agent.cpp:4:10: fatal error: glog/logging.h: No such file or directory
    4 | #include <glog/logging.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/agent.dir/build.make:63: CMakeFiles/agent.dir/src/agent.cpp.o] Error 1
make[3]: Leaving directory '/home/yyt/Downloads/craftassist/client'
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/agent.dir/all] Error 2
make[2]: Leaving directory '/home/yyt/Downloads/craftassist/client'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/home/yyt/Downloads/craftassist/client'
make: *** [Makefile:20: client] Error 2

**Comment by niansong1996** [comment]
@yutongyan Hi! I've met with the same issue, so I am wondering how you solved it?

**Comment by yutongyan** [comment]
@niansong1996 Hey! I tried to solve some errors and it worked. But there are too many to fix manually. I guess the errors are due to incompatible versions of GCC/G++. I opened a new issue to ask their GCC version. FYI, I have the newest GCC.

**Comment by niansong1996** [comment]
@yutongyan Thanks! I am actually using CLANG since I am compiling it on macOS. And different LLVM version gives different compilation errors, so I am guessing I have compatibility issues as well.
