### ISSUE TITLE
I could not install streamlit

### ISSUE THREAD

**Issue by kinsomaz** [facebookresearch/craftassist#44]
Commad errored out with exit status 1

**Comment by kavyasrinet** [comment]
Hi, 
Could you please provide more context around the issue ? We tried looking into this and cannot figure out where this is being installed

**Comment by kavyasrinet** [comment]
Hi @kinsomaz !
We will be closing this issue for now.
We'll also be sending out a heads-up over email but we have now migrated the `craftassist` codebase to be here: https://github.com/facebookresearch/droidlet and we will be maintaining this repo going forward. We ask that you please switch to the `droidlet` repo going forward. 
Please feel free to reopen the issue under the `droidlet` repo if you still need help.
