### ISSUE TITLE
Use with Minecraft Education Edition Client

### ISSUE THREAD

**Issue by kolbytn** [facebookresearch/craftassist#45]
I'm trying to connect to the craftassist cuberite instance with Minecraft Education Edition. Is this possible? I'm using the docker build with WSL2 on Windows 10.

**Comment by kolbytn** [comment]
Note that I only want to be able to see what the agent is doing. If there is a better way to do that let me know.

**Comment by kavyasrinet** [comment]
Hi,
Thanks for creating the issue. We haven't really done any work on the client side so the rendering is done entirely on the client side. We have support for 1.12.x (https://github.com/facebookresearch/craftassist#error-unsupported-protocol-version) . You will need the client to be able to render a video of the agent or see it from a third person's perspective.

We haven't tested it with Minecraft Education Edition. You said you tried it ? We are curious to know what exactly happened when you did so.

**Comment by kolbytn** [comment]
I tried it with Minecraft education edition, but the client would not connect to the cuberite instance.
![education_edition](https://user-images.githubusercontent.com/25499651/94854139-4d0aa400-03e1-11eb-901f-65e7afffbaff.PNG)
I've read that with education edition `Multiplayer is possible for players within the same Office 365 tenant`. Is there a way to set the account that the cuberite instance is started under? I wonder if that might work.
I also tried using the malmo client, but that didn't work either.
![malmo](https://user-images.githubusercontent.com/25499651/94854578-fbaee480-03e1-11eb-8bec-acc804e0ae50.PNG)
I have an official minecraft client that is working, but I'd like to be able to have other students work on projects with craftassist without requiring everyone to purchase the official version.

**Comment by kavyasrinet** [comment]
Unfortunately everyone would need an official Minecraft client for it to render the world and agent.
cc'ing @snyxan here to take a look as well.

**Comment by snyxan** [comment]
Hi @kolbytn,

Unfortunately we can not bypass education edition restriction in cuberite side now and it's difficult for us to look into it since we do not have an education edition MC. 

You are welcome to explore potential solution for it. Let me know if you need help!

**Comment by kavyasrinet** [comment]
Hi @kolbytn !
We will be closing this issue for now.
We'll also be sending out a headsup over email but we have now migrated the `craftassist` codebase to be here: https://github.com/facebookresearch/droidlet and we will be maintaining this repo going forward. We ask that you please switch to the `droidlet` repo going forward. 
Please feel free to reopen the issue under the `droidlet` repo if you still need help.
