### ISSUE TITLE
Failed to install via docker...

### ISSUE THREAD

**Issue by poyotamu000** [facebookresearch/craftassist#47]
I did these commands, but errors occur.
Please help me.

```
cd craftassist/docker
docker build -t craftassist -f Dockerfile.client .
```

```
Sending build context to Docker daemon  24.06kB
Step 1/20 : FROM ubuntu:18.04
 ---> 56def654ec22
Step 2/20 : RUN apt-get -y update
 ---> Using cache
 ---> a1370438b032
Step 3/20 : RUN apt-get install -y      curl         cmake         g++         git         libboost-all-dev         libeigen3-dev         libgoogle-glog-dev         make         python3-dev         python3-pip         ;
 ---> Using cache
 ---> ddda43a3e9f0
Step 4/20 : RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
 ---> Using cache
 ---> c4db60594586
Step 5/20 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> 5b962a655ab5
Step 6/20 : RUN pip3 install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
 ---> Using cache
 ---> 3c56f6bee127
Step 7/20 : ADD . /craftassist
 ---> 313ac8f69d49
Step 8/20 : WORKDIR /craftassist
 ---> Running in e0728cc5fab8
Removing intermediate container e0728cc5fab8
 ---> eed45cf9e301
Step 9/20 : RUN curl http://craftassist.s3-us-west-2.amazonaws.com/pubr/models_folder.tar.gz -o models_folder.tar.gz
 ---> Running in 4e2861525d9c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1618M  100 1618M    0     0  3339k      0  0:08:16  0:08:16 --:--:-- 4792k
Removing intermediate container 4e2861525d9c
 ---> a4967598b67f
Step 10/20 : RUN tar -xzvf models_folder.tar.gz -C python/craftassist/models/ --strip-components 1
 ---> Running in a370a12f73a5
tar: python/craftassist/models: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
The command '/bin/sh -c tar -xzvf models_folder.tar.gz -C python/craftassist/models/ --strip-components 1' returned a non-zero code: 2
```

**Comment by snyxan** [comment]
Hey @poyotamu000, glad to help here!

Please try the following instead: 
```
cd craftassist
docker build -t craftassist -f ./docker/Dockerfile.client .
```

We recommend to use the script [local_install.sh](https://github.com/facebookresearch/craftassist/blob/master/docker/local_install.sh) we provided for local docker installation. In that way local `python` folder is mounted to docker container so that any local code changes can be reflected in a real-time manner.

**Comment by feipenghe** [comment]
Follow the previous instruction, I got another error. Can you help me out? Thanks!

```
Step 15/20 : RUN make
 ---> Running in 64e1f8ae44b0
cd cuberite && \
mkdir -p Release && \
cd Release && \
cmake -DCMAKE_BUILD_TYPE=RELEASE .. && \
make -j`nproc`
CMake Error: The source directory "/craftassist/cuberite" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:15: recipe for target 'cuberite' failed
make: *** [cuberite] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
```

**Comment by feipenghe** [comment]
> Follow the previous instruction, I got another error. Can you help me out? Thanks!
> 
> ```
> Step 15/20 : RUN make
>  ---> Running in 64e1f8ae44b0
> cd cuberite && \
> mkdir -p Release && \
> cd Release && \
> cmake -DCMAKE_BUILD_TYPE=RELEASE .. && \
> make -j`nproc`
> CMake Error: The source directory "/craftassist/cuberite" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.
> Makefile:15: recipe for target 'cuberite' failed
> make: *** [cuberite] Error 1
> The command '/bin/sh -c make' returned a non-zero code: 2
> ```

@snyxan

**Comment by snyxan** [comment]
> @snyxan Follow the previous instruction, I got another error. Can you help me out? Thanks!
> 
> ```
> Step 15/20 : RUN make
>  ---> Running in 64e1f8ae44b0
> cd cuberite && \
> mkdir -p Release && \
> cd Release && \
> cmake -DCMAKE_BUILD_TYPE=RELEASE .. && \
> make -j`nproc`
> CMake Error: The source directory "/craftassist/cuberite" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.
> Makefile:15: recipe for target 'cuberite' failed
> make: *** [cuberite] Error 1
> The command '/bin/sh -c make' returned a non-zero code: 2
> ```

Hey @feipenghe ,

Are you using  [local_install.sh](https://github.com/facebookresearch/craftassist/blob/master/docker/local_install.sh) or not?

I couldn't repro your error easily on my end. Could you please share your environment settings? Thanks.

**Comment by feipenghe** [comment]
@snyxan 

Initially, I installed docker myself and tried the first commands. 
```
cd craftassist/docker
docker build -t craftassist -f Dockerfile.client .
```
I had the same error as @poyotamu000 . Then I used used [local_install.sh](https://github.com/facebookresearch/craftassist/blob/master/docker/local_install.sh)
And got the error as above. 

Not sure it's the issue of previous docker installation.

**Comment by snyxan** [comment]
> Not sure it's the issue of previous docker installation.

@feipenghe It could be docker using a cached layer from previous failed installation. Try building without caching using the following command:

```
cd craftassist/docker
docker build --no-cache -t craftassist -f ./docker/Dockerfile.client .
```

**Comment by feipenghe** [comment]
@snyxan Previous bug is because I didn't install the submodule. After that, I found a new bug.
```
-- Lua has NOT been found in your system, the build will use its own Lua implementation.
CMake Error at CMakeLists.txt:210 (message):
  SQLiteCpp is missing in folder lib/SQLiteCpp.  Have you initialized the
  submodules / downloaded the extra libraries?


-- Configuring incomplete, errors occurred!
See also "/craftassist/cuberite/Release/CMakeFiles/CMakeOutput.log".
make: *** [cuberite] Error 1
Makefile:15: recipe for target 'cuberite' failed
The command '/bin/sh -c make' returned a non-zero code: 2
Unable to find image 'minecraft:latest' locally
docker: Error response from daemon: pull access denied for minecraft, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by feipenghe** [comment]
I think I found the problem. There are still some submodules I haven't installed yet.

**Comment by kavyasrinet** [comment]
Thanks for confirming @feipenghe ! We'll now close the issue. 
We'll also be sending out a headsup over email but we have now migrated the `craftassist` codebase to be here: https://github.com/facebookresearch/droidlet and we will be maintaining this repo going forward. We ask that you please switch to the `droidlet` repo going forward. 
Please feel free to reopen the issue there if you see the issue again.
