### ISSUE TITLE
How to run agent?

### ISSUE THREAD

**Issue by feipenghe** [facebookresearch/craftassist#49]
I successfully setup everything except for agent by using local_install.sh. 
There are two instructions for running agents. 
For the first one `docker exec -it craftassist-container bash`, I don't have craftassist-container.
For the second one `python ./python/craftassist/craftassist_agent.py`, I don't have all the dependencies downloaded. It gives me another error when I try to download packages.

What should I do with it?

**Comment by snyxan** [comment]
Hi @feipenghe ,

For the first one, you will need to create a container from the docker image you created as discussed in [previous issue](https://github.com/facebookresearch/craftassist/issues/47) using the following command:
```
docker run -it -p 25565:25565 -p 3000:3000 -p 2556:2556 -p 2557:2557 -p 9000:9000 -p 5000:5000 -p 8000:8000 -v "$(pwd)"/python:/craftassist/python -v "$(pwd)"/annotation_tools:/craftassist/annotation_tools --name craftassist_container craftassist
```
This will create the container, start it and open an interactive bash shell for you. Then you can use ```docker exec -it craftassist-container bash``` to open as many bash shell as you want.
If you are using [local_install.sh](https://github.com/facebookresearch/craftassist/blob/master/docker/local_install.sh) the name would be minecraft for the image and minecraft_container for the container. The above steps are the same.

For the second one, could you please share what errors you get when you try to download packages? Are you using these [instructions](https://github.com/facebookresearch/craftassist#python-requirements-using-a-conda-environment)?

**Comment by feipenghe** [comment]
Thanks, I think I didn't understand how to use docker container. I realize python script should be run in the container.
