### ISSUE TITLE
Recreating https://craftassist.io

### ISSUE THREAD

**Issue by kayburns** [facebookresearch/craftassist#52]
Would it be possible to include code and documentation for setting up something like [https://craftassist.io](https://craftassist.io)? Or at least documentation for launching new cuberite+agent instances through aws (which is what I assume craftassist.io is using)?

**Comment by snyxan** [comment]
Hi @kayburns,

The code for setting up https://craftassist.io is internal-only right now and we're not planning to open source it in the near term. May I ask why you want to set up something like that? What is your use case?

If you don't want to run it locally, we have a section in [README](https://github.com/facebookresearch/craftassist#option-a-docker) giving instructions about how to set up using Docker container.

**Comment by kayburns** [comment]
Hi @snyxan,

Thank you for the response. I'm interested in collecting user interaction data over mturk.

**Comment by kavyasrinet** [comment]
Hi @kayburns ! Thanks for creating the issue.
We are planning on open sourcing the code we have used to host craftassist.io soon. We'll also be sending out a headsup over email but we have now migrated the craftassist codebase to be here: https://github.com/facebookresearch/droidlet and will be maintaining this repo going forward. Please switch to droidlet for future updates and features.
