### ISSUE TITLE
Problem with Import path/File present

### ISSUE THREAD

**Issue by eximer168** [facebookresearch/craftassist#9]
Can't figure out why this import path is not finding file, occurs when activating agent: (see below)

Followed all the procedures, dependancies installed, using stock virtualbox install of Ubuntu 18.04 on windows 10.
Applied python3 link fix (https://github.com/facebookresearch/craftassist/issues/7);
didn't seem to make any difference, Cuberite  is operational

$ python ./python/craftassist/craftassist_agent.py

Received error:
python3 ./python/craftassist/craftassist_agent.py
Traceback (most recent call last):
  File "./python/craftassist/craftassist_agent.py", line 31, in <module>
    import default_behaviors
  File "/home/dev/Desktop/craftassist/python/craftassist/default_behaviors.py", line 13, in <module>
    from dialogue_objects import Say
  File "/home/dev/Desktop/craftassist/python/craftassist/dialogue_objects/__init__.py", line 1, in <module>
    from .interpreter import Interpreter
  File "/home/dev/Desktop/craftassist/python/craftassist/dialogue_objects/interpreter.py", line 12, in <module>
    from .interpreter_helper import (
  File "/home/dev/Desktop/craftassist/python/craftassist/dialogue_objects/interpreter_helper.py", line 6, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'

**Comment by youkarin** [comment]
I think you can ues this:

pip3 install python-Levenshtein

**Comment by kavyasrinet** [comment]
We have included a [requirements.txt](https://github.com/facebookresearch/craftassist/blob/master/requirements.txt) file in the repo.
can you run:
`pip install -r requirements.txt` before you proceed ?
I'll add this to the README as well.

**Comment by eximer168** [comment]
> We have included a [requirements.txt](https://github.com/facebookresearch/craftassist/blob/master/requirements.txt) file in the repo.
> can you run:
> `pip install -r requirements.txt` before you proceed ?
> I'll add this to the README as well.

Yes that did it! Hurrah.
For anyone running stock Ubuntu.
sudo pip3 install -r requirements.txt    plus

**Comment by kavyasrinet** [comment]
Great, closing this issue for now!
